/* eslint-disable no-console */
const fs = require('fs');
const path = require('path');

function loadDeployment(dir, name) {
  const p = path.join(dir, `${name}.json`);
  if (!fs.existsSync(p)) return null;
  const j = JSON.parse(fs.readFileSync(p, 'utf8'));
  return { address: j.address, abi: j.abi };
}

function loadArtifact(root, name) {
  const p = path.join(root, `artifacts/contracts/${name}.sol/${name}.json`);
  if (!fs.existsSync(p)) return null;
  const j = JSON.parse(fs.readFileSync(p, 'utf8'));
  return { address: '0x0000000000000000000000000000000000000000', abi: j.abi };
}

function generateTs(outPath, dist, ceth) {
  const src = `// Auto-generated by scripts/sync-abis.js
export const DISTRIBUTOR_ADDRESS = '${dist.address}';
export const DISTRIBUTOR_ABI = ${JSON.stringify(dist.abi, null, 2)} as const;
export const CONFIDENTIAL_ETH_ADDRESS = '${ceth.address}';
export const CONFIDENTIAL_ETH_ABI = ${JSON.stringify(ceth.abi, null, 2)} as const;
`;
  fs.writeFileSync(outPath, src);
  console.log(`Wrote ${outPath}`);
}

function main() {
  const root = process.cwd();
  const sepoliaDir = path.join(root, 'deployments', 'sepolia');
  const out = path.join(root, 'home', 'src', 'config', 'contracts.ts');

  let dist = loadDeployment(sepoliaDir, 'Distributor');
  let ceth = loadDeployment(sepoliaDir, 'ConfidentialETH');

  if (!dist || !ceth) {
    console.warn('deployments/sepolia not found or incomplete. Falling back to artifacts.');
    dist = loadArtifact(root, 'Distributor');
    ceth = loadArtifact(root, 'ConfidentialETH');
  }

  if (!dist || !ceth) throw new Error('Cannot find ABIs');
  generateTs(out, dist, ceth);
}

main();

